=== RM4862/tecweb/p1/josueenhz-practicas-tecweb-5a6b52b43a7b/practicas/p11/p11-serviciovod/serviciovod.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT catalogoVOD (cuenta+, contenido)>
<!ELEMENT cuenta (perfiles)>
<!ELEMENT perfiles (perfil+)>
<!ELEMENT perfil (#PCDATA)>
<!ATTLIST cuenta correo CDATA #REQUIRED >
<!ATTLIST perfil 
usuario CDATA #REQUIRED
idioma CDATA #REQUIRED>

<!ELEMENT contenido (peliculas, programas)>
<!ELEMENT peliculas (genero+)>
<!ELEMENT genero (titulo+)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST genero nombre CDATA #REQUIRED >
<!ATTLIST titulo duracion CDATA #REQUIRED >
<!ELEMENT programas (genero+)>

=== RM4862/tecweb/p1/josueenhz-practicas-tecweb-5a6b52b43a7b/practicas/p11/p11-serviciovod/08-serviciovod2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogoVOD SYSTEM "serviciovod.dtd">

<catalogoVOD>
    <cuenta correo = "correo@gmail.com">
        <perfiles>
            <perfil usuario = "Usuario_1" idioma = "Español"/>
            <perfil usuario = "Usuario_2" idioma = "Español"/>
        </perfiles>
    </cuenta>
    
    <contenido>
        <peliculas>
            <genero nombre = "Terror">
                <titulo duracion="1h 5m">Host</titulo>
                <titulo duracion="1h 51m">Maligno</titulo>
                <titulo duracion="2h 15m">IT</titulo>
                <titulo duracion="1h 43m">La noche del demonio</titulo>                
            </genero>
            <genero nombre = "Romance">
                <titulo duracion="2h 5m">El poder del perro</titulo>
                <titulo duracion="1h 54m">El tiempo contigo</titulo>
                <titulo duracion="1h 52m">Your name</titulo>
                <titulo duracion="1h 50m">Yo antes de ti</titulo>
            </genero>
        </peliculas>
        
        <programas>
            <genero nombre = "Comedia">
                <titulo duracion="13 temporadas">Bob Esponja</titulo>
                <titulo duracion="33 temporadas">Los Simpson</titulo> 
                <titulo duracion="20 temporadas">Padre de Familia</titulo> 
                <titulo duracion="4 temporadas">Escandalosos</titulo>                 
            </genero>
            <genero nombre = "Ciencia Ficcion">                
                <titulo duracion="5 temporadas">Black Mirror</titulo>
                <titulo duracion="3 temporadas">Dark</titulo>
                <titulo duracion="3 temporadas">Viajeros</titulo>
                <titulo duracion="3 temporadas">Star Trek</titulo>                
            </genero>
        </programas>
    </contenido>
    
</catalogoVOD>
